#
# Copyright © 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

FROM --platform=${BUILDPLATFORM} node:22 AS builder
ARG NODE_OPTIONS=""
ENV NODE_OPTIONS=${NODE_OPTIONS}
WORKDIR /workspace/
ADD . /workspace/
RUN npm ci
RUN npm run build:dev

# Remove devDependencies and keep production dependencies
RUN npm prune --production

FROM node:22-alpine
WORKDIR /workspace/
COPY --from=builder /workspace/dist /workspace/
COPY --from=builder /workspace/node_modules /workspace/node_modules
COPY --from=builder /workspace/package.json /workspace/package.json
USER root
RUN echo "alias ll='ls -ahl'" >> /root/.bashrc
RUN apk add --update --no-cache supervisor vim bash

RUN chmod -R 1777 /tmp /var/tmp /workspace

# Define build arguments
ARG GIT_BRANCH
ARG GIT_COMMIT
ARG BUILD_TIME
ARG DOCKERFILE

# Set the environment variables
ENV GIT_BRANCH=${GIT_BRANCH}
ENV GIT_COMMIT=${GIT_COMMIT}
ENV BUILD_TIME=${BUILD_TIME}
ENV DOCKERFILE=${DOCKERFILE}

CMD [ "/usr/bin/supervisord", "-c", "/workspace/server/supervisord.conf" ]
EXPOSE 80 9229
